### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by diomed** [JohnMica/grav-theme-bulma-portfolio#3]
hi

before anything , can there be some working demo of a page?

Why is your logo in the theme?
Doesn't seem to be ability to remove it / replace it easily via admin panel.

**Comment by JohnMica** [comment]
The demo is coming (few days max) - other work that pays the bills 

I had to put a logo so it is mine. You can change it in the actual files (this something to consider in the next release)

**Comment by JohnMica** [comment]
just updated the theme (build 0.1.5) 

- you can choose the logo and the favicon from the theme settings but only after you have created a page, saved it and uploaded media to the page (this is the only workaround right now that I can think of)

- demo content added, so when you install the theme you should be prompted to back-up your current pages

**Comment by diomed** [comment]
ok. thank you

**Comment by diomed** [comment]
btw. just thought you should know - looks like your theme does not update on grav package repository.

**Comment by JohnMica** [comment]
thanks man, but it should update once the GPM will update itself - every some hours it should work

**Comment by diomed** [comment]
if you go on https://getgrav.org/downloads/themes you'll see that theme version is still 0.1.0
and for every updated theme people who use it get notification automatically that there is an update.
for yours that's not the case. hence, something's wrong.

**Comment by JohnMica** [comment]
This is a strange one. I’ll investigate it and hope to fix it.

**Comment by diomed** [comment]
btw. out of curiosity, did you build this on top of haywire?

**Comment by JohnMica** [comment]
Initial inspiration was the Story theme. 

But I’ve added some other things / elements. 

Based on Bulma templates 

Regards,

John Mica

**Comment by diomed** [comment]
no demo yet?

**Comment by JohnMica** [comment]
There is a demo folder which will install when you install the theme. 

Do you mean a website to demo the theme? That I haven’t done yet

Regards,

John Mica

**Comment by diomed** [comment]
yes, I mean a website

**Comment by JohnMica** [comment]
Got it. I’ll make one these days and update the links here and on the Grav website. 

Regards,

John Mica
